In [ ]:
!pip install -q langchain-text-splitters

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [315]:
from langchain_text_splitters import (
    CharacterTextSplitter,
    RecursiveCharacterTextSplitter,
    MarkdownHeaderTextSplitter,
    NLTKTextSplitter
)
from pathlib import Path
import re
import nltk

import pandas as pd

import json

In [313]:
# LEIRUTA DOS ARQUIVOS NAS PASTAS
PASTA = Path("/content/sample_data/mds")
documentos = []


def ler_arquivos(PASTA):
    arquivos = list(PASTA.glob("**/*.md"))

    for arquivo in arquivos:
        texto = arquivo.read_text(encoding="utf-8")

        documentos.append({
            "arquivo": arquivo.name,
            "caminho": str(arquivo),
            #"texto": texto
        })

        #print(documentos)

        # Passa pelos arquivos
        for item in documentos:
            print("Arquivo:", item['arquivo'])
            print("Caminho:", item['caminho'])
    return arquivos

arquivos = ler_arquivos(PASTA)

Arquivo: attention_is_all_you_need.md
Caminho: /content/sample_data/mds/attention_is_all_you_need.md

# Variaveis Globais

In [254]:
resultados_todos = []

# Chamadas de Funções Principais.

In [314]:
resultados_todos = []
def start_app():
  print("Execução em andamento . . .")
  executar()
  executar_teste7()
  executar_teste8()
  executar_teste9()
  executar_teste10()
  print("Criando tabela . . .")
  executar_tabela()
  gerar_json()

start_app()

Execução em andamento . . .

WARNING:langchain_text_splitters.base:Created a chunk of size 9506, which is longer than the specified 4000

{'Qtd. chunks': 136, 'Tamanho médio': 358.71, 'Tamanho mínimo': 22, 'Tamanho máximo': 499, 'Chunks': ['Provided proper attribution is provided, Google hereby grants permission to reproduce the tables and figures in this paper solely for use in journalistic or scholarly works.\n\n## Attention Is All You Need\n\nAshish Vaswani ∗ Google Brain avaswani@google.com Noam Shazeer ∗ Google Brain noam@google.com', 'Llion Jones ∗ Google Research llion@google.com Niki Parmar ∗ Google Research nikip@google.com Aidan N. Gomez ∗ † University of Toronto aidan@cs.toronto.edu Jakob Uszkoreit ∗ Google Research usz@google.com Łukasz Kaiser ∗ Google Brain lukaszkaiser@google.com Illia Polosukhin ∗ ‡\n\nillia.polosukhin@gmail.com\n\n## Abstract', 'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being', 'more parallelizable and requiring significantly less time to train. Our model achieves 28.4 BLEU on the WMT 2014 Englishto-German translation task, improving over the existing best results, including ensembles, by over 2 BLEU. On the WMT 2014 English-to-French translation task, our model establishes a new single-model state-of-the-art BLEU score of 41.8 after training for 3.5 days on eight GPUs, a small fraction of the training costs of the best models from the literature. We show that the', 'the Transformer generalizes well to other tasks by applying it successfully to English constituency parsing both with large and limited training data.', '∗ Equal contribution. Listing order is random. Jakob proposed replacing RNNs with self-attention and started the effort to evaluate this idea. Ashish, with Illia, designed and implemented the first Transformer models and has been crucially involved in every aspect of this work. Noam proposed scaled dot-product attention, multi-head attention and the parameter-free position representation and became the other person involved in nearly every detail. Niki designed, implemented, tuned and evaluated', 'countless model variants in our original codebase and tensor2tensor. Llion also experimented with novel model variants, was responsible for our initial codebase, and efficient inference and visualizations. Lukasz and Aidan spent countless long days designing various parts of and implementing tensor2tensor, replacing our earlier codebase, greatly improving results and massively accelerating our research.', '† Work performed while at Google Brain.\n\n‡ Work performed while at Google Research.\n\n## 1 Introduction', 'Recurrent neural networks, long short-term memory [13] and gated recurrent [7] neural networks in particular, have been firmly established as state of the art approaches in sequence modeling and transduction problems such as language modeling and machine translation [35, 2, 5]. Numerous efforts have since continued to push the boundaries of recurrent language models and encoder-decoder architectures [38, 24, 15].', 'Recurrent models typically factor computation along the symbol positions of the input and output sequences. Aligning the positions to steps in computation time, they generate a sequence of hidden states h t , as a function of the previous hidden state h t -1 and the input for position t . This inherently sequential nature precludes parallelization within training examples, which becomes critical at longer sequence lengths, as memory constraints limit batching across examples. Recent work has', 'has achieved significant improvements in computational efficiency through factorization tricks [21] and conditional computation [32], while also improving model performance in case of the latter. The fundamental constraint of sequential computation, however, remains.', 'Attention mechanisms have become an integral part of compelling sequence modeling and transduction models in various tasks, allowing modeling of dependencies without regard to their distance in the input or output sequences [2, 19]. In all but a few cases [27], however, such attention mechanisms are used in conjunction with a recurrent network.', 'In this work we propose the Transformer, a model architecture eschewing recurrence and instead relying entirely on an attention mechanism to draw global dependencies between input and output. The Transformer allows for significantly more parallelization and can reach a new state of the art in translation quality after being trained for as little as twelve hours on eight P100 GPUs.\n\n## 2 Background', 'The goal of reducing sequential computation also forms the foundation of the Extended Neural GPU [16], ByteNet [18] and ConvS2S [9], all of which use convolutional neural networks as basic building block, computing hidden representations in parallel for all input and output positions. In these models, the number of operations required to relate signals from two arbitrary input or output positions grows in the distance between positions, linearly for ConvS2S and logarithmically for ByteNet. This', 'This makes it more difficult to learn dependencies between distant positions [12]. In the Transformer this is reduced to a constant number of operations, albeit at the cost of reduced effective resolution due to averaging attention-weighted positions, an effect we counteract with Multi-Head Attention as described in section 3.2.', 'Self-attention, sometimes called intra-attention is an attention mechanism relating different positions of a single sequence in order to compute a representation of the sequence. Self-attention has been used successfully in a variety of tasks including reading comprehension, abstractive summarization, textual entailment and learning task-independent sentence representations [4, 27, 28, 22].', 'End-to-end memory networks are based on a recurrent attention mechanism instead of sequencealigned recurrence and have been shown to perform well on simple-language question answering and language modeling tasks [34].', 'To the best of our knowledge, however, the Transformer is the first transduction model relying entirely on self-attention to compute representations of its input and output without using sequencealigned RNNs or convolution. In the following sections, we will describe the Transformer, motivate self-attention and discuss its advantages over models such as [17, 18] and [9].\n\n## 3 Model Architecture', 'Most competitive neural sequence transduction models have an encoder-decoder structure [5, 2, 35]. Here, the encoder maps an input sequence of symbol representations ( x 1 , ..., x n ) to a sequence of continuous representations z = ( z 1 , ..., z n ) . Given z , the decoder then generates an output sequence ( y 1 , ..., y m ) of symbols one element at a time. At each step the model is auto-regressive [10], consuming the previously generated symbols as additional input when generating the next.', 'Figure 1: The Transformer - model architecture.\n\n<!-- image -->\n\nThe Transformer follows this overall architecture using stacked self-attention and point-wise, fully connected layers for both the encoder and decoder, shown in the left and right halves of Figure 1, respectively.\n\n## 3.1 Encoder and Decoder Stacks', 'Encoder: The encoder is composed of a stack of N = 6 identical layers. Each layer has two sub-layers. The first is a multi-head self-attention mechanism, and the second is a simple, positionwise fully connected feed-forward network. We employ a residual connection [11] around each of the two sub-layers, followed by layer normalization [1]. That is, the output of each sub-layer is LayerNorm( x +Sublayer( x )) , where Sublayer( x ) is the function implemented by the sub-layer itself. To', 'To facilitate these residual connections, all sub-layers in the model, as well as the embedding layers, produce outputs of dimension d model = 512 .', 'Decoder: The decoder is also composed of a stack of N = 6 identical layers. In addition to the two sub-layers in each encoder layer, the decoder inserts a third sub-layer, which performs multi-head attention over the output of the encoder stack. Similar to the encoder, we employ residual connections around each of the sub-layers, followed by layer normalization. We also modify the self-attention sub-layer in the decoder stack to prevent positions from attending to subsequent positions. This', 'This masking, combined with fact that the output embeddings are offset by one position, ensures that the predictions for position i can depend only on the known outputs at positions less than i .', '## 3.2 Attention\n\nAn attention function can be described as mapping a query and a set of key-value pairs to an output, where the query, keys, values, and output are all vectors. The output is computed as a weighted sum\n\n## Scaled Dot-Product Attention\n\n<!-- image -->\n\nFigure 2: (left) Scaled Dot-Product Attention. (right) Multi-Head Attention consists of several attention layers running in parallel.\n\n<!-- image -->', 'of the values, where the weight assigned to each value is computed by a compatibility function of the query with the corresponding key.\n\n## 3.2.1 Scaled Dot-Product Attention\n\nWe call our particular attention "Scaled Dot-Product Attention" (Figure 2). The input consists of queries and keys of dimension d k , and values of dimension d v . We compute the dot products of the query with all keys, divide each by √ d k , and apply a softmax function to obtain the weights on the values.', 'In practice, we compute the attention function on a set of queries simultaneously, packed together into a matrix Q . The keys and values are also packed together into matrices K and V . We compute the matrix of outputs as:\n\n<!-- formula-not-decoded -->', 'The two most commonly used attention functions are additive attention [2], and dot-product (multiplicative) attention. Dot-product attention is identical to our algorithm, except for the scaling factor of 1 √ d k . Additive attention computes the compatibility function using a feed-forward network with a single hidden layer. While the two are similar in theoretical complexity, dot-product attention is much faster and more space-efficient in practice, since it can be implemented using highly', 'optimized matrix multiplication code.', 'While for small values of d k the two mechanisms perform similarly, additive attention outperforms dot product attention without scaling for larger values of d k [3]. We suspect that for large values of d k , the dot products grow large in magnitude, pushing the softmax function into regions where it has extremely small gradients 4 . To counteract this effect, we scale the dot products by 1 √ d k .\n\n## 3.2.2 Multi-Head Attention', 'Instead of performing a single attention function with d model-dimensional keys, values and queries, we found it beneficial to linearly project the queries, keys and values h times with different, learned linear projections to d k , d k and d v dimensions, respectively. On each of these projected versions of queries, keys and values we then perform the attention function in parallel, yielding d v -dimensional output values. These are concatenated and once again projected, resulting in the final', 'values, as depicted in Figure 2.', '4 To illustrate why the dot products get large, assume that the components of q and k are independent random variables with mean 0 and variance 1 . Then their dot product, q · k = ∑ d k i =1 q i k i , has mean 0 and variance d k .\n\nMulti-head attention allows the model to jointly attend to information from different representation subspaces at different positions. With a single attention head, averaging inhibits this.\n\n<!-- formula-not-decoded -->', 'Where the projections are parameter matrices W Q i ∈ R d model × d k , W i K ∈ R d model × d k , W V i ∈ R d model × d v and W O ∈ R hd v × d model .\n\nIn this work we employ h = 8 parallel attention layers, or heads. For each of these we use d k = d v = d model /h = 64 . Due to the reduced dimension of each head, the total computational cost is similar to that of single-head attention with full dimensionality.\n\n## 3.2.3 Applications of Attention in our Model', 'The Transformer uses multi-head attention in three different ways:', '- In "encoder-decoder attention" layers, the queries come from the previous decoder layer, and the memory keys and values come from the output of the encoder. This allows every position in the decoder to attend over all positions in the input sequence. This mimics the typical encoder-decoder attention mechanisms in sequence-to-sequence models such as [38, 2, 9].', '- The encoder contains self-attention layers. In a self-attention layer all of the keys, values and queries come from the same place, in this case, the output of the previous layer in the encoder. Each position in the encoder can attend to all positions in the previous layer of the encoder.', '- Similarly, self-attention layers in the decoder allow each position in the decoder to attend to all positions in the decoder up to and including that position. We need to prevent leftward information flow in the decoder to preserve the auto-regressive property. We implement this inside of scaled dot-product attention by masking out (setting to -∞ ) all values in the input of the softmax which correspond to illegal connections. See Figure 2.', '## 3.3 Position-wise Feed-Forward Networks\n\nIn addition to attention sub-layers, each of the layers in our encoder and decoder contains a fully connected feed-forward network, which is applied to each position separately and identically. This consists of two linear transformations with a ReLU activation in between.\n\n<!-- formula-not-decoded -->', 'While the linear transformations are the same across different positions, they use different parameters from layer to layer. Another way of describing this is as two convolutions with kernel size 1. The dimensionality of input and output is d model = 512 , and the inner-layer has dimensionality d ff = 2048 .\n\n## 3.4 Embeddings and Softmax', 'Similarly to other sequence transduction models, we use learned embeddings to convert the input tokens and output tokens to vectors of dimension d model. We also use the usual learned linear transformation and softmax function to convert the decoder output to predicted next-token probabilities. In our model, we share the same weight matrix between the two embedding layers and the pre-softmax linear transformation, similar to [30]. In the embedding layers, we multiply those weights by √ d model.', 'Table 1: Maximum path lengths, per-layer complexity and minimum number of sequential operations for different layer types. n is the sequence length, d is the representation dimension, k is the kernel size of convolutions and r the size of the neighborhood in restricted self-attention.', '| Layer Type                  | Complexity per Layer   | Sequential Operations   | Maximum Path Length   |\n|-----------------------------|------------------------|-------------------------|-----------------------|\n| Self-Attention              | O ( n 2 · d )          | O (1)                   | O (1)                 |\n| Recurrent                   | O ( n · d 2 )          | O ( n )                 | O ( n )               |', '| Convolutional               | O ( k · n · d 2 )      | O (1)                   | O ( log k ( n ))      |\n| Self-Attention (restricted) | O ( r · n · d )        | O (1)                   | O ( n/r )             |', '## 3.5 Positional Encoding', 'Since our model contains no recurrence and no convolution, in order for the model to make use of the order of the sequence, we must inject some information about the relative or absolute position of the tokens in the sequence. To this end, we add "positional encodings" to the input embeddings at the bottoms of the encoder and decoder stacks. The positional encodings have the same dimension d model as the embeddings, so that the two can be summed. There are many choices of positional encodings,', 'learned and fixed [9].', 'In this work, we use sine and cosine functions of different frequencies:\n\n<!-- formula-not-decoded -->', 'where pos is the position and i is the dimension. That is, each dimension of the positional encoding corresponds to a sinusoid. The wavelengths form a geometric progression from 2 π to 10000 · 2 π . We chose this function because we hypothesized it would allow the model to easily learn to attend by relative positions, since for any fixed offset k , PE pos + k can be represented as a linear function of PE pos .', 'We also experimented with using learned positional embeddings [9] instead, and found that the two versions produced nearly identical results (see Table 3 row (E)). We chose the sinusoidal version because it may allow the model to extrapolate to sequence lengths longer than the ones encountered during training.\n\n## 4 Why Self-Attention', 'In this section we compare various aspects of self-attention layers to the recurrent and convolutional layers commonly used for mapping one variable-length sequence of symbol representations ( x 1 , ..., x n ) to another sequence of equal length ( z 1 , ..., z n ) , with x i , z i ∈ R d , such as a hidden layer in a typical sequence transduction encoder or decoder. Motivating our use of self-attention we consider three desiderata.', 'One is the total computational complexity per layer. Another is the amount of computation that can be parallelized, as measured by the minimum number of sequential operations required.', 'The third is the path length between long-range dependencies in the network. Learning long-range dependencies is a key challenge in many sequence transduction tasks. One key factor affecting the ability to learn such dependencies is the length of the paths forward and backward signals have to traverse in the network. The shorter these paths between any combination of positions in the input and output sequences, the easier it is to learn long-range dependencies [12]. Hence we also compare the', 'the maximum path length between any two input and output positions in networks composed of the different layer types.', 'As noted in Table 1, a self-attention layer connects all positions with a constant number of sequentially executed operations, whereas a recurrent layer requires O ( n ) sequential operations. In terms of computational complexity, self-attention layers are faster than recurrent layers when the sequence length n is smaller than the representation dimensionality d , which is most often the case with sentence representations used by state-of-the-art models in machine translations, such as', 'as word-piece [38] and byte-pair [31] representations. To improve computational performance for tasks involving very long sequences, self-attention could be restricted to considering only a neighborhood of size r in the input sequence centered around the respective output position. This would increase the maximum path length to O ( n/r ) . We plan to investigate this approach further in future work.', 'A single convolutional layer with kernel width k &lt; n does not connect all pairs of input and output positions. Doing so requires a stack of O ( n/k ) convolutional layers in the case of contiguous kernels, or O ( log k ( n )) in the case of dilated convolutions [18], increasing the length of the longest paths between any two positions in the network. Convolutional layers are generally more expensive than recurrent layers, by a factor of k . Separable convolutions [6], however, decrease the', 'the complexity considerably, to O ( k · n · d + n · d 2 ) . Even with k = n , however,

,Arquivo,Teste,Estratégia,Configuração,Qtd. chunks,Tamanho médio,Tamanho mínimo,Tamanho máximo,Chunks sobrepostos,Overlap (%),Tokens estimados,Chunks
0,attention_is_all_you_need.md,1,Fixo,"200 caracteres, overlap 0",245,192.89,117,200,0.0,0.0,11814.0,"[Provided proper attribution is provided, Goog..."
1,attention_is_all_you_need.md,2,Fixo,"500 caracteres, overlap 0",98,492.66,425,500,0.0,0.0,12070.0,"[Provided proper attribution is provided, Goog..."
2,attention_is_all_you_need.md,3,Fixo,"1000 caracteres, overlap 0",49,993.20,937,1000,0.0,0.0,12167.0,"[Provided proper attribution is provided, Goog..."
3,attention_is_all_you_need.md,4,Fixo,"2000 caracteres, overlap 0",25,1951.04,956,2000,0.0,0.0,12194.0,"[Provided proper attribution is provided, Goog..."
4,attention_is_all_you_need.md,5,Fixo + overlap,"500 caracteres, overlap 50",109,491.54,357,500,108.0,10.0,13394.0,"[Provided proper attribution is provided, Goog..."
5,attention_is_all_you_need.md,6,Fixo + overlap,"500 caracteres, overlap 200",163,492.30,357,500,162.0,40.0,20061.0,"[Provided proper attribution is provided, Goog..."
6,attention_is_all_you_need.md,7,Por parágrafo,"500 caracteres, overlap 50",136,358.71,22,499,NaN,NaN,NaN,"[Provided proper attribution is provided, Goog..."
7,attention_is_all_you_need.md,8,Sentenças agrupadas,3 sentenças por chunk,5,10086.60,1620,14045,NaN,NaN,NaN,[{'texto': 'Provided proper attribution is pro...
8,attention_is_all_you_need.md,9,Recursive Character,"500 caracteres, overlap 50",137,364.13,26,499,NaN,NaN,NaN,"[Provided proper attribution is provided, Goog..."
9,attention_is_all_you_need.md,10,Markdown / estrutura semântica,"#, ##, ###",28,1750.11,12,10946,NaN,NaN,NaN,"[Provided proper attribution is provided, Goog..."

Arquivo salvo em: resultados.json

In [253]:
# Para testes 1 - 6
executar()

{'Qtd. chunks': 123, 'Tamanho médio': 339.69, 'Tamanho mínimo': 1, 'Tamanho máximo': 499, 'Chunks': ['## Escrita acadêmica ética, responsável e humana com inteligência artificial\n\n<!-- image -->\n\nRafael Cardoso Sampaio\n\n## I ✉\n\nI Programa Pós-Graduação em Ciência Política, Universidade Federal do Paraná, Curitiba, PR, Brasil.\n\nPalavras-chave: escrita acadêmica, integridade científica, Inteligência Artificial Generativa, autoria, revisão narrativa.', 'RESUMO Introdução: A rápida disseminação da inteligência artificial generativa (IAG) transformou práticas de escrita acadêmica, ampliando a eficiência, mas levantando preocupações sobre autoria, integridade, privacidade e desenvolvimento cognitivo. A literatura recente tem se concentrado em debates normativos e em políticas institucionais sobre autoria e transparência, mas oferece pouca orientação operacional sobre como utilizar a IA sem comprometer a formação intelectual, especialmente entre', "jovens pesquisadores(as). Este artigo busca preencher essa lacuna ao propor um método estruturado de uso ético, responsável e humano da IA. Materiais e métodos: Oestudo realiza uma revisão narrativa de literatura sobre riscos associados à escrita com IA (e.g., diluição da autoria, descarregamento cognitivo, vieses, privacidade e 'alucinações') e integra essa revisão com documentos normativos e diretrizes institucionais. A partir dessa síntese, o artigo desenvolve um guia prático composto por", 'por cinco fases metodológicas para orientar o uso crítico da tecnologia. Resultados: Oguia proposto organiza o processo de escrita em etapas: planejamento humano prévio; escrita assistida e curadoria crítica; apropriação e reescrita autoral; verificação rigorosa de fatos, fontes e lógica argumentativa; e responsabilidade final com declaração transparente do uso de IA. Cada fase fornece salvaguardas para mitigar riscos cognitivos, éticos e epistêmicos, preservando a agência autoral. Discussão:', 'Argumenta-se que o uso ético da IA depende menos de proibições formais e mais do desenvolvimento de práticas de vigilância intelectual, documentação e reflexão contínua. Embora o processo reduza parte da eficiência oferecida pela IA, contribui para fortalecer competências cognitivas, proteger a integridade científica e equilibrar inovação tecnológica com responsabilidade humana.', 'Recebido em 23 de Julho de 2025. Aprovado em 5 de Novembro de 2025. Aceito em 2 de Dezembro de 2025.\n\nEditor Científico: Adriano Codato\n\nEditor Associado: Adriano Codato\n\niD\n\n<!-- image -->\n\n<!-- image -->\n\n## I. Introdução\n\nOficina de Escrita Acadêmica\n\nRevista de Sociologia e Política\n\nDOI 10.1590/1678-98732433e018', 'A integração da inteligência artificial generativa (IAG) na produção de conhecimento acadêmico, acelerada por ferramentas como o ChatGPT, evoluiu rapidamente de uma postura de cautela para uma adoção ampla, motivada especialmente pela promessa de maior eficiência. A capacidade de automatizar ou acelerar diversas fases do trabalho acadêmico gerou otimismo (Pereira et al., 2024). Contudo, essa incorporação massiva também levanta questionamentos sobre a integridade da pesquisa, a originalidade do', 'do pensamento e o desenvolvimento das competências cognitivas dos próprios acadêmicos (Lopes et al., 2024; Sampaio et al., 2024).', 'A resposta inicial da academia concentrou-se em debates normativos e filosóficos. Uma parte considerável da literatura recente dedicou-se a investigar os limites da autoria, questionando se uma entidade não humana poderia ser creditada em trabalhos científicos. A conclusão predominante é que a IA funciona como ferramenta, pois não possui agência ou responsabilidade legal e moral por suas produções (Resnik &amp; Hosseini, 2025). Em paralelo, outro foco dominante foi a criação de políticas', 'institucionais, que frequentemente enquadram o uso de IA sob a ótica da desonestidade acadêmica, refletindo a preocupação em proteger os valores tradicionais da produção de conhecimento e valorizando práticas de total transparência (Trindade &amp; Oliveira, 2024).', 'Apesar de relevante, a discussão normativa vigente deixa uma lacuna de orientação prática para estudantes e jovens pesquisadores sobre como utilizar a IA de forma ética, sem comprometer o desenvolvimento intelectual (Winberg et al., 2024). A ausência de um método claro agrava os perigos às fundações cognitivas e criativas da produção de conhecimento, manifestando-se em três áreas críticas.', 'O primeiro risco diz respeito à diluição da autoria. A autoria manifesta a voz singular de um pesquisador, mas a colaboração com IA pode esvaziar o processo criativo ao transferir tarefas intelectuais para a máquina (Floridi, 2025). Estudos demonstram que, mesmo melhorando a qualidade textual, o uso de IA pode reduzir a satisfação intrínseca que alimenta a motivação acadêmica (Mei et al., 2025). Essa delegação pode levar à fixação de ideias e à redução da autoconfiança criativa, uma vez que a', 'a criatividade humana opera com base em associações idiossincráticas, enquanto a IA gera textos derivativos e estatisticamente prováveis (Lopes et al., 2024).', 'O segundo risco envolve o descarregamento cognitivo ( cognitive offloading ). A delegação de tarefas mentais diminui o engajamento com o pensamento crítico e a aprendizagem autônoma. Evidências mostram que o uso de IA sem salvaguardas resulta em desempenho inferior em avaliações posteriores, sugerindo que o suporte tecnológico contínuo mina a resolução independente de problemas (Jin et al., 2025; Lee et al., 2025). Com o tempo, essa dependência pode atrofiar capacidades cognitivas essenciais', '(Lopes et al., 2024; Sampaio et al., 2024).', 'O terceiro risco tange à privacidade e propriedade intelectual. Ao interagir com ferramentas de IA, pesquisadores expõem ideias e rascunhos ao treinamento de modelos, gerando questões de confidencialidade (Winberg et al., 2024). A falta de transparência sobre o uso de dados protegidos agrava o cenário (Bai et al., 2024; Sampaio et al., 2024). Além disso, a natureza derivativa dos modelos cria riscos tangíveis de plágio inadvertido (Pereira et al., 2024).', 'Este artigo busca preencher a lacuna de orientação prática, oferecendo um guia metodológico para o escrita acadêmica ética, responsável e humana com inteligência artificial com ênfase na Ciência Política e voltado especialmente para jovens pesquisadores e estudantes ainda receosos em utilizar a IA em seus trabalhos. O uso ético refere-se à adesão aos princípios de integridade científica (não fabricar dados, não plagiar); o uso responsável tange à transparência algorítmica e à privacidade de', 'de dados de pesquisa; já o uso humano diz respeito à preservação da agência e da voz do pesquisador, impedindo que a tecnologia substitua o pensamento crítico.', 'O guia é estruturado em cinco fases que orientam o pesquisador para uma colaboração ética e responsável, assegurando que a autoria humana permaneça central no processo. Nesse sentido, em vez de focar somente no que evitar, o objetivo é mostrar como unir a eficiência da máquina com a prevalência do pensamento humano, lidando diretamente com os três riscos aqui apresentados.\n\n## II. Guia prático para uso ético, responsável e humano da IA generativa na escrita acadêmica', 'Diante de tais desafios, elaboramos um guia prático composto por sete etapas a serem observadas durante a escrita com IA buscando equilíbrio entre um uso ético, responsável e que valorize o humano. O Quadro 1 resume as etapas para efeitos didáticos.\n\nQuadro 1 - Etapas para uso ético, responsável e humano da IA na escrita acadêmica', '|              | Fase                                       | Foco Principal                                                 | Objetivo                                                                                                   |\n|--------------|--------------------------------------------|----------------------------------------------------------------|------------------------------------------------------------------------------------------------------------|', '| Pré- escrita | 1. Planejamento humano para o uso de IA    | Estruturação pré-IA, proteção de dados e engenharia de prompts | Garantir a intenção autoral, proteger dados de pesquisa e dominar princípios de interação com IA.          |\n| Escrita      | 2. Escrita assistida e cu- radoria crítica | Brainstorming , análise e revisão contínua                     | Usar a IA para expandir ideias, aprofundar refle- xão crítica e refinar progressivamente o conteúdo.       |', '|              | 3. Apropriação e reescrita autoral         | Transformação e personalização do texto                        | Infundir a voz, pensamento e estilo do autor, ga- rantindo originalidade e evitando marcas algorít- micas. |\n| Pós- escrita | 4. Verificação rigorosa de fatos e fontes  | Validação independente de infor- mações                        | Assegurar a precisão factual, bibliográfica, lógica e ausência de plágio.                                  |', '|              | 5. Responsabilidade final e transparência  | Accountability e declaração de uso                             | Assumir responsabilidade integral pelo trabalho e declarar transparentemente o uso de IA.                  |', 'Fonte: elaborado pelo autor (2025).\n\n## II.1. Fase 1: planejamento humano para o uso de IA', 'A proteção de dados sensíveis que possam identificar participantes de uma pesquisa é uma consideração central ao utilizar inteligência artificial. A inserção de qualquer informação confidencial, como relatos pessoais ou dados que permitam a identificação de indivíduos, deve ser evitada em plataformas públicas de IA. O manejo inadequado dessas informações pode levar a violações de privacidade e ao descumprimento de regulamentações de proteção de dados (Trindade &amp; Oliveira, 2024). A', 'A anonimização completa dos dados, removendo quaisquer identificadores pessoais antes da interação com ferramentas de IA, é recomendada para salvaguardar a confidencialidade dos participantes.', 'Outra dimensão de cuidado refere-se à preservação do ineditismo e do capital intelectual da pesquisa. Pesquisadores manifestam apreensão de que seus achados originais, uma vez inseridos em uma plataforma de IA, possam se tornar parte da informação geral disponível online. Os modelos de linguagem são continuamente treinados com os dados que recebem, e qualquer informação fornecida pode ser incorporada ao seu conjunto de treinamento e, eventualmente, ser reapresentada em interações com outros', 'usuários (Pereira et al., 2024; Sampaio et al., 2024). Como cada plataforma estabelece suas próprias regras quanto à privacidade dos dados e ao uso dessas informações para treinamento dos modelos, o pesquisador deve conhecer as políticas de cada ferramenta antes de seu uso.', "Ainda antes da escrita com IA, a principal orientação é: 'nunca comece pelo chat'. Toda escrita acadêmica rigorosa deve ser iniciada fora das ferramentas de inteligência artificial. O pesquisador deve primeiro estabelecer as fundações intelectuais do trabalho mapeando a tese central, formulando perguntas de pesquisa e esboçando o esqueleto do texto. Essa estruturação prévia fortalece a intenção autoral e mitiga que o algoritmo dite a narrativa ou limite o escopo criativo (Pereira et al., 2024;", 'Mollick &amp; Mollick, 2024). A criatividade genuína emerge de conexões inesperadas e pensamento que vão além de dados de treinamento, enquanto a IA opera com padrões estatísticos de alta probabilidade, tornando-se usualmente inadequada para inovação conceitual (Lopes et al., 2024; Resnik &amp; Hosseini, 2025).', 'Na pesquisa em Ciência Política, isso significa, entre outras coisas, definir o desenho de pesquisa de forma independente. Antes de solicitar à IA que', "'escreva uma introdução', o pesquisador deve ter clareza sobre quatro elementos. O primeiro é a pergunta de pesquisa, que delimita o que está sendo investigado e, preferencialmente, explicita uma relação causal a ser testada, por exemplo 'Qual o impacto das emendas parlamentares na coesão partidária no Brasil pós-2018?'. O segundo é a hipótese de trabalho, que oferece uma resposta provisória para guiar o estudo. O terceiro é o marco teórico, que define as lentes conceituais da análise, como", 'como institucionalismo de escolha racional ou sociologia política. O quarto é a estratégia metodológica, que define como a hipótese será testada empiricamente, seja por métodos quantitativos, qualitativos ou mistos.', 'Definido o planejamento, o pesquisador deve escolher as ferramentas e dominar os princípios de interação com a IA. Há uma vasta gama de ferramentas disponíveis (ver Sampaio et al., 2024; Trindade &amp; Oliveira, 2024). As plataformas de IA geralmente oferecem algum tipo de editor de texto com possibilidades de escrita, dentre os quais você deverá escolher (ver Apêndice). Não obstante, muitas ferramentas funcionam como extensões que você pode adicionar ao seu editor de texto, como o Microsoft', 'Word e o Google Docs, sendo que as próprias empresas já embutiram ferramentas do tipo em seus editores. Aqui, o principal cuidado é que algumas ferramentas são especializadas na escrita acadêmica e outras são generalistas, merecendo mais cuidado, além disso, cada plataforma estabelece suas próprias regras quanto à privacidade dos dados e ao uso dessas informações para treinamento dos modelos.', "Os chats dos modelos de linguagem, como ChatGPT, DeepSeek e afins, também podem auxiliar na escrita acadêmica. A qualidade dos resultados é diretamente proporcional à precisão do comando fornecido, prática conhecida como 'engenharia de prompts ' (Trindade &amp; Oliveira, 2024). Em vez de fazer perguntas genéricas, o pesquisador deve assumir o papel de um 'designer de narrativas', como sugere Floridi (2025), especificando os requisitos, restrições e parâmetros da tarefa (para mais, ver Sampaio", '&amp; Figueiredo, 2025).', "Grosso modo, deve-se atribuir um papel ou função específica à IA para converte-la em uma assistente especializada e não em ferramenta generalista. Comandos como 'atue como pesquisador sênior especialista em instituições políticas e relações Executivo Legislativo' ou 'assuma o papel de um parecerista de periódico e me dê sugestões e pontos a serem melhorados no seguinte texto' tendem a ser efetivos. Essa definição ajuda a IA a compreender o tipo de saída ( output ) esperado e aumenta a precisão", 'das respostas (Mollick &amp; Mollick, 2024).', "Além de definir um papel, o prompt deve fornecer um contexto claro, incluindo a tarefa exata a ser realizada, incluindo o formato , o público-alvo , e o estilo de escrita desejado, o que maximiza a relevância do resultado (Trindade &amp; Oliveira, 2024), como 'corrija esta seção de discussão teórica sobre a governabilidade na Nova República pós-1988. O público-alvo são pares acadêmicos especializados em instituições políticas brasileiras. Mantenha tom analítico e formal. Utilize o vocabulário", "conceitual consagrado pela literatura brasileira sobre o presidencialismo de coalizão, incluindo conceitos como 'poderes de agenda', 'disciplina partidária', 'formação de gabinetes' e 'custos de transação legislativos'. A seção deve ter entre 1.500 e 2.000 palavras, estruturada em parágrafos argumentativos sem uso de listas ou marcadores. Justifique as alterações realizadas ao texto'. Em muitos casos, é bom fornecer contextos maiores, como anexar um artigo ou colar um texto dentro da temática", 'que você deseja escrever.', '## II.2. Fase 2: geração de insumos, curadoria crítica e refinamento iterativo', 'Uma vez escolhidas as ferramentas e dominados os princípios de engenharia de prompts , torna-se possível interagir com a inteligência artificial de maneira controlada, utilizando-a como um recurso de apoio para ampliar o repertório criativo e analítico, sem substituir a capacidade de análise crítica. Um uso profícuo consiste em solicitar à IA a geração de listas de ideias sobre um tópico, a sugestão de diferentes ângulos para um argumento, a criação de exemplos para ilustrar conceitos ou a', "ou a elaboração de analogias para teorias complexas (Mollick &amp; Mollick, 2024). Essa abordagem transforma a IA em uma 'parceira de brainstorming ' ou em uma 'fonte de inspiração' e uma 'bússola' que aponta novas direções (Jin et al., 2025). A IA pode aumentar a fluência e a flexibilidade do pensamento divergente, auxiliando na superação de bloqueios criativos.", "Assim como o trabalho não começa no chat, ele também não termina nele. Nenhuma resposta produzida por IA deve ser tratada como versão final. Cada trecho de texto produzido pela máquina é um protótipo, um rascunho inicial que exige um rigoroso processo de curadoria e apropriação humana. Em vez de aceitar passivamente a primeira sugestão, que frequentemente é genérica e carece de profundidade (Pereira et al., 2024), o pesquisador deve guiar a ferramenta com comandos específicos, a exemplo de 'sua", "'sua sugestão anterior foi útil, mas agora a refine para incorporar o debate sobre a execução de emendas parlamentares como moeda de troca nas relações Executivo-Legislativo e remover as generalizações sobre barganha política em sistemas presidencialistas'.", "Esta fase se define por ciclos curtos e contínuos de revisão, nos quais o pesquisador lê criticamente o material, identifica imprecisões, superficialidades ou lacunas argumentativas ('Escrever', 'Filtrar', 'Verificar'), e utiliza essas observações para refinar seus prompts em um diálogo contínuo com a ferramenta (Bai et al., 2024). Ess e ciclo de interação e refinamento progressivo não só melhora a qualidade do resultado da máquina, mas também ajuda o próprio pesquisador a clarificar seus", 'seus objetivos e a aprofundar seu pensamento crítico (Lee et al., 2025), mantendo total agência e controle sobre o conteúdo (Floridi, 2025).', "Uma forma de aprofundar esse processo é inverter a dinâmica da interação, solicitando que a IA atue como uma 'entrevistadora' ou 'crítica socrática' para desafiar a lógica do trabalho humano. Comandos como 'leia este parágrafo sobre o conceito de polarização afetiva e aponte três falhas lógicas ou contra-argumentos baseados na literatura recente' ou 'aja como um aluno iniciante e peça para eu explicar este conceito em termos simples' forçam o autor a defender e a clarificar suas ideias,", "quebrando o que Mollick &amp; Mollick (2024) denominam 'ilusão de profundidade explanatória', quando acreditamos entender um tópico mais profundamente do que de fato entendemos.", "Muitas ferramentas de escrita com IA permitem você selecionar um texto e pedir para a máquina 'melhorar a escrita', 'deixar mais formal', 'simplificar a linguagem', 'corrigir ortografia e gramática', 'encurtar', 'alongar' ou 'mudar o tom', como é o exemplo do Gemini, que é capaz de editar o texto diretamente no Google Docs (ver Apêndice). Prefira esse tipo de opção mais detida em pequenos trechos, evitando opções generalistas que escrevem trechos completos, como 'escrever introdução", "(conclusão)' ou 'escrever com argumentos opostos' (ver Apêndice). Mas todas essas opções, na prática, significam que seu texto vai ser reescrito por uma IA generativa.", "Da mesma maneira, ao usar chats de grandes modelos de linguagem, como ChatGPT, Qwen, DeepSeek e afins, sempre prefira prompts que peçam para revisar ou melhorar o trecho com 'justificativas para as mudanças', o que garante que você compreenda as razões pelas quais a máquina está mexendo no seu texto e te exercita a compreender tais sugestões. Esse exercício de avaliação das justificativas funciona como prática reflexiva, utilizando a IA como um 'espelho' para testar a robustez dos próprios", "argumentos (Jin et al., 2025). Uma alternativa é solicitar que o chat ofereça 'duas ou mais opções de correção'. Dessa maneira, você poderá observar as diferentes alternativas e construir seu próprio texto. A experiência mostra que a familiaridad

In [227]:
executar_teste7()

{'Qtd. chunks': 123, 'Tamanho médio': 339.69, 'Tamanho mínimo': 1, 'Tamanho máximo': 499, 'Chunks': ['## Escrita acadêmica ética, responsável e humana com inteligência artificial\n\n<!-- image -->\n\nRafael Cardoso Sampaio\n\n## I ✉\n\nI Programa Pós-Graduação em Ciência Política, Universidade Federal do Paraná, Curitiba, PR, Brasil.\n\nPalavras-chave: escrita acadêmica, integridade científica, Inteligência Artificial Generativa, autoria, revisão narrativa.', 'RESUMO Introdução: A rápida disseminação da inteligência artificial generativa (IAG) transformou práticas de escrita acadêmica, ampliando a eficiência, mas levantando preocupações sobre autoria, integridade, privacidade e desenvolvimento cognitivo. A literatura recente tem se concentrado em debates normativos e em políticas institucionais sobre autoria e transparência, mas oferece pouca orientação operacional sobre como utilizar a IA sem comprometer a formação intelectual, especialmente entre', "jovens pesquisadores(as). Este artigo busca preencher essa lacuna ao propor um método estruturado de uso ético, responsável e humano da IA. Materiais e métodos: Oestudo realiza uma revisão narrativa de literatura sobre riscos associados à escrita com IA (e.g., diluição da autoria, descarregamento cognitivo, vieses, privacidade e 'alucinações') e integra essa revisão com documentos normativos e diretrizes institucionais. A partir dessa síntese, o artigo desenvolve um guia prático composto por", 'por cinco fases metodológicas para orientar o uso crítico da tecnologia. Resultados: Oguia proposto organiza o processo de escrita em etapas: planejamento humano prévio; escrita assistida e curadoria crítica; apropriação e reescrita autoral; verificação rigorosa de fatos, fontes e lógica argumentativa; e responsabilidade final com declaração transparente do uso de IA. Cada fase fornece salvaguardas para mitigar riscos cognitivos, éticos e epistêmicos, preservando a agência autoral. Discussão:', 'Argumenta-se que o uso ético da IA depende menos de proibições formais e mais do desenvolvimento de práticas de vigilância intelectual, documentação e reflexão contínua. Embora o processo reduza parte da eficiência oferecida pela IA, contribui para fortalecer competências cognitivas, proteger a integridade científica e equilibrar inovação tecnológica com responsabilidade humana.', 'Recebido em 23 de Julho de 2025. Aprovado em 5 de Novembro de 2025. Aceito em 2 de Dezembro de 2025.\n\nEditor Científico: Adriano Codato\n\nEditor Associado: Adriano Codato\n\niD\n\n<!-- image -->\n\n<!-- image -->\n\n## I. Introdução\n\nOficina de Escrita Acadêmica\n\nRevista de Sociologia e Política\n\nDOI 10.1590/1678-98732433e018', 'A integração da inteligência artificial generativa (IAG) na produção de conhecimento acadêmico, acelerada por ferramentas como o ChatGPT, evoluiu rapidamente de uma postura de cautela para uma adoção ampla, motivada especialmente pela promessa de maior eficiência. A capacidade de automatizar ou acelerar diversas fases do trabalho acadêmico gerou otimismo (Pereira et al., 2024). Contudo, essa incorporação massiva também levanta questionamentos sobre a integridade da pesquisa, a originalidade do', 'do pensamento e o desenvolvimento das competências cognitivas dos próprios acadêmicos (Lopes et al., 2024; Sampaio et al., 2024).', 'A resposta inicial da academia concentrou-se em debates normativos e filosóficos. Uma parte considerável da literatura recente dedicou-se a investigar os limites da autoria, questionando se uma entidade não humana poderia ser creditada em trabalhos científicos. A conclusão predominante é que a IA funciona como ferramenta, pois não possui agência ou responsabilidade legal e moral por suas produções (Resnik &amp; Hosseini, 2025). Em paralelo, outro foco dominante foi a criação de políticas', 'institucionais, que frequentemente enquadram o uso de IA sob a ótica da desonestidade acadêmica, refletindo a preocupação em proteger os valores tradicionais da produção de conhecimento e valorizando práticas de total transparência (Trindade &amp; Oliveira, 2024).', 'Apesar de relevante, a discussão normativa vigente deixa uma lacuna de orientação prática para estudantes e jovens pesquisadores sobre como utilizar a IA de forma ética, sem comprometer o desenvolvimento intelectual (Winberg et al., 2024). A ausência de um método claro agrava os perigos às fundações cognitivas e criativas da produção de conhecimento, manifestando-se em três áreas críticas.', 'O primeiro risco diz respeito à diluição da autoria. A autoria manifesta a voz singular de um pesquisador, mas a colaboração com IA pode esvaziar o processo criativo ao transferir tarefas intelectuais para a máquina (Floridi, 2025). Estudos demonstram que, mesmo melhorando a qualidade textual, o uso de IA pode reduzir a satisfação intrínseca que alimenta a motivação acadêmica (Mei et al., 2025). Essa delegação pode levar à fixação de ideias e à redução da autoconfiança criativa, uma vez que a', 'a criatividade humana opera com base em associações idiossincráticas, enquanto a IA gera textos derivativos e estatisticamente prováveis (Lopes et al., 2024).', 'O segundo risco envolve o descarregamento cognitivo ( cognitive offloading ). A delegação de tarefas mentais diminui o engajamento com o pensamento crítico e a aprendizagem autônoma. Evidências mostram que o uso de IA sem salvaguardas resulta em desempenho inferior em avaliações posteriores, sugerindo que o suporte tecnológico contínuo mina a resolução independente de problemas (Jin et al., 2025; Lee et al., 2025). Com o tempo, essa dependência pode atrofiar capacidades cognitivas essenciais', '(Lopes et al., 2024; Sampaio et al., 2024).', 'O terceiro risco tange à privacidade e propriedade intelectual. Ao interagir com ferramentas de IA, pesquisadores expõem ideias e rascunhos ao treinamento de modelos, gerando questões de confidencialidade (Winberg et al., 2024). A falta de transparência sobre o uso de dados protegidos agrava o cenário (Bai et al., 2024; Sampaio et al., 2024). Além disso, a natureza derivativa dos modelos cria riscos tangíveis de plágio inadvertido (Pereira et al., 2024).', 'Este artigo busca preencher a lacuna de orientação prática, oferecendo um guia metodológico para o escrita acadêmica ética, responsável e humana com inteligência artificial com ênfase na Ciência Política e voltado especialmente para jovens pesquisadores e estudantes ainda receosos em utilizar a IA em seus trabalhos. O uso ético refere-se à adesão aos princípios de integridade científica (não fabricar dados, não plagiar); o uso responsável tange à transparência algorítmica e à privacidade de', 'de dados de pesquisa; já o uso humano diz respeito à preservação da agência e da voz do pesquisador, impedindo que a tecnologia substitua o pensamento crítico.', 'O guia é estruturado em cinco fases que orientam o pesquisador para uma colaboração ética e responsável, assegurando que a autoria humana permaneça central no processo. Nesse sentido, em vez de focar somente no que evitar, o objetivo é mostrar como unir a eficiência da máquina com a prevalência do pensamento humano, lidando diretamente com os três riscos aqui apresentados.\n\n## II. Guia prático para uso ético, responsável e humano da IA generativa na escrita acadêmica', 'Diante de tais desafios, elaboramos um guia prático composto por sete etapas a serem observadas durante a escrita com IA buscando equilíbrio entre um uso ético, responsável e que valorize o humano. O Quadro 1 resume as etapas para efeitos didáticos.\n\nQuadro 1 - Etapas para uso ético, responsável e humano da IA na escrita acadêmica', '|              | Fase                                       | Foco Principal                                                 | Objetivo                                                                                                   |\n|--------------|--------------------------------------------|----------------------------------------------------------------|------------------------------------------------------------------------------------------------------------|', '| Pré- escrita | 1. Planejamento humano para o uso de IA    | Estruturação pré-IA, proteção de dados e engenharia de prompts | Garantir a intenção autoral, proteger dados de pesquisa e dominar princípios de interação com IA.          |\n| Escrita      | 2. Escrita assistida e cu- radoria crítica | Brainstorming , análise e revisão contínua                     | Usar a IA para expandir ideias, aprofundar refle- xão crítica e refinar progressivamente o conteúdo.       |', '|              | 3. Apropriação e reescrita autoral         | Transformação e personalização do texto                        | Infundir a voz, pensamento e estilo do autor, ga- rantindo originalidade e evitando marcas algorít- micas. |\n| Pós- escrita | 4. Verificação rigorosa de fatos e fontes  | Validação independente de infor- mações                        | Assegurar a precisão factual, bibliográfica, lógica e ausência de plágio.                                  |', '|              | 5. Responsabilidade final e transparência  | Accountability e declaração de uso                             | Assumir responsabilidade integral pelo trabalho e declarar transparentemente o uso de IA.                  |', 'Fonte: elaborado pelo autor (2025).\n\n## II.1. Fase 1: planejamento humano para o uso de IA', 'A proteção de dados sensíveis que possam identificar participantes de uma pesquisa é uma consideração central ao utilizar inteligência artificial. A inserção de qualquer informação confidencial, como relatos pessoais ou dados que permitam a identificação de indivíduos, deve ser evitada em plataformas públicas de IA. O manejo inadequado dessas informações pode levar a violações de privacidade e ao descumprimento de regulamentações de proteção de dados (Trindade &amp; Oliveira, 2024). A', 'A anonimização completa dos dados, removendo quaisquer identificadores pessoais antes da interação com ferramentas de IA, é recomendada para salvaguardar a confidencialidade dos participantes.', 'Outra dimensão de cuidado refere-se à preservação do ineditismo e do capital intelectual da pesquisa. Pesquisadores manifestam apreensão de que seus achados originais, uma vez inseridos em uma plataforma de IA, possam se tornar parte da informação geral disponível online. Os modelos de linguagem são continuamente treinados com os dados que recebem, e qualquer informação fornecida pode ser incorporada ao seu conjunto de treinamento e, eventualmente, ser reapresentada em interações com outros', 'usuários (Pereira et al., 2024; Sampaio et al., 2024). Como cada plataforma estabelece suas próprias regras quanto à privacidade dos dados e ao uso dessas informações para treinamento dos modelos, o pesquisador deve conhecer as políticas de cada ferramenta antes de seu uso.', "Ainda antes da escrita com IA, a principal orientação é: 'nunca comece pelo chat'. Toda escrita acadêmica rigorosa deve ser iniciada fora das ferramentas de inteligência artificial. O pesquisador deve primeiro estabelecer as fundações intelectuais do trabalho mapeando a tese central, formulando perguntas de pesquisa e esboçando o esqueleto do texto. Essa estruturação prévia fortalece a intenção autoral e mitiga que o algoritmo dite a narrativa ou limite o escopo criativo (Pereira et al., 2024;", 'Mollick &amp; Mollick, 2024). A criatividade genuína emerge de conexões inesperadas e pensamento que vão além de dados de treinamento, enquanto a IA opera com padrões estatísticos de alta probabilidade, tornando-se usualmente inadequada para inovação conceitual (Lopes et al., 2024; Resnik &amp; Hosseini, 2025).', 'Na pesquisa em Ciência Política, isso significa, entre outras coisas, definir o desenho de pesquisa de forma independente. Antes de solicitar à IA que', "'escreva uma introdução', o pesquisador deve ter clareza sobre quatro elementos. O primeiro é a pergunta de pesquisa, que delimita o que está sendo investigado e, preferencialmente, explicita uma relação causal a ser testada, por exemplo 'Qual o impacto das emendas parlamentares na coesão partidária no Brasil pós-2018?'. O segundo é a hipótese de trabalho, que oferece uma resposta provisória para guiar o estudo. O terceiro é o marco teórico, que define as lentes conceituais da análise, como", 'como institucionalismo de escolha racional ou sociologia política. O quarto é a estratégia metodológica, que define como a hipótese será testada empiricamente, seja por métodos quantitativos, qualitativos ou mistos.', 'Definido o planejamento, o pesquisador deve escolher as ferramentas e dominar os princípios de interação com a IA. Há uma vasta gama de ferramentas disponíveis (ver Sampaio et al., 2024; Trindade &amp; Oliveira, 2024). As plataformas de IA geralmente oferecem algum tipo de editor de texto com possibilidades de escrita, dentre os quais você deverá escolher (ver Apêndice). Não obstante, muitas ferramentas funcionam como extensões que você pode adicionar ao seu editor de texto, como o Microsoft', 'Word e o Google Docs, sendo que as próprias empresas já embutiram ferramentas do tipo em seus editores. Aqui, o principal cuidado é que algumas ferramentas são especializadas na escrita acadêmica e outras são generalistas, merecendo mais cuidado, além disso, cada plataforma estabelece suas próprias regras quanto à privacidade dos dados e ao uso dessas informações para treinamento dos modelos.', "Os chats dos modelos de linguagem, como ChatGPT, DeepSeek e afins, também podem auxiliar na escrita acadêmica. A qualidade dos resultados é diretamente proporcional à precisão do comando fornecido, prática conhecida como 'engenharia de prompts ' (Trindade &amp; Oliveira, 2024). Em vez de fazer perguntas genéricas, o pesquisador deve assumir o papel de um 'designer de narrativas', como sugere Floridi (2025), especificando os requisitos, restrições e parâmetros da tarefa (para mais, ver Sampaio", '&amp; Figueiredo, 2025).', "Grosso modo, deve-se atribuir um papel ou função específica à IA para converte-la em uma assistente especializada e não em ferramenta generalista. Comandos como 'atue como pesquisador sênior especialista em instituições políticas e relações Executivo Legislativo' ou 'assuma o papel de um parecerista de periódico e me dê sugestões e pontos a serem melhorados no seguinte texto' tendem a ser efetivos. Essa definição ajuda a IA a compreender o tipo de saída ( output ) esperado e aumenta a precisão", 'das respostas (Mollick &amp; Mollick, 2024).', "Além de definir um papel, o prompt deve fornecer um contexto claro, incluindo a tarefa exata a ser realizada, incluindo o formato , o público-alvo , e o estilo de escrita desejado, o que maximiza a relevância do resultado (Trindade &amp; Oliveira, 2024), como 'corrija esta seção de discussão teórica sobre a governabilidade na Nova República pós-1988. O público-alvo são pares acadêmicos especializados em instituições políticas brasileiras. Mantenha tom analítico e formal. Utilize o vocabulário", "conceitual consagrado pela literatura brasileira sobre o presidencialismo de coalizão, incluindo conceitos como 'poderes de agenda', 'disciplina partidária', 'formação de gabinetes' e 'custos de transação legislativos'. A seção deve ter entre 1.500 e 2.000 palavras, estruturada em parágrafos argumentativos sem uso de listas ou marcadores. Justifique as alterações realizadas ao texto'. Em muitos casos, é bom fornecer contextos maiores, como anexar um artigo ou colar um texto dentro da temática", 'que você deseja escrever.', '## II.2. Fase 2: geração de insumos, curadoria crítica e refinamento iterativo', 'Uma vez escolhidas as ferramentas e dominados os princípios de engenharia de prompts , torna-se possível interagir com a inteligência artificial de maneira controlada, utilizando-a como um recurso de apoio para ampliar o repertório criativo e analítico, sem substituir a capacidade de análise crítica. Um uso profícuo consiste em solicitar à IA a geração de listas de ideias sobre um tópico, a sugestão de diferentes ângulos para um argumento, a criação de exemplos para ilustrar conceitos ou a', "ou a elaboração de analogias para teorias complexas (Mollick &amp; Mollick, 2024). Essa abordagem transforma a IA em uma 'parceira de brainstorming ' ou em uma 'fonte de inspiração' e uma 'bússola' que aponta novas direções (Jin et al., 2025). A IA pode aumentar a fluência e a flexibilidade do pensamento divergente, auxiliando na superação de bloqueios criativos.", "Assim como o trabalho não começa no chat, ele também não termina nele. Nenhuma resposta produzida por IA deve ser tratada como versão final. Cada trecho de texto produzido pela máquina é um protótipo, um rascunho inicial que exige um rigoroso processo de curadoria e apropriação humana. Em vez de aceitar passivamente a primeira sugestão, que frequentemente é genérica e carece de profundidade (Pereira et al., 2024), o pesquisador deve guiar a ferramenta com comandos específicos, a exemplo de 'sua", "'sua sugestão anterior foi útil, mas agora a refine para incorporar o debate sobre a execução de emendas parlamentares como moeda de troca nas relações Executivo-Legislativo e remover as generalizações sobre barganha política em sistemas presidencialistas'.", "Esta fase se define por ciclos curtos e contínuos de revisão, nos quais o pesquisador lê criticamente o material, identifica imprecisões, superficialidades ou lacunas argumentativas ('Escrever', 'Filtrar', 'Verificar'), e utiliza essas observações para refinar seus prompts em um diálogo contínuo com a ferramenta (Bai et al., 2024). Ess e ciclo de interação e refinamento progressivo não só melhora a qualidade do resultado da máquina, mas também ajuda o próprio pesquisador a clarificar seus", 'seus objetivos e a aprofundar seu pensamento crítico (Lee et al., 2025), mantendo total agência e controle sobre o conteúdo (Floridi, 2025).', "Uma forma de aprofundar esse processo é inverter a dinâmica da interação, solicitando que a IA atue como uma 'entrevistadora' ou 'crítica socrática' para desafiar a lógica do trabalho humano. Comandos como 'leia este parágrafo sobre o conceito de polarização afetiva e aponte três falhas lógicas ou contra-argumentos baseados na literatura recente' ou 'aja como um aluno iniciante e peça para eu explicar este conceito em termos simples' forçam o autor a defender e a clarificar suas ideias,", "quebrando o que Mollick &amp; Mollick (2024) denominam 'ilusão de profundidade explanatória', quando acreditamos entender um tópico mais profundamente do que de fato entendemos.", "Muitas ferramentas de escrita com IA permitem você selecionar um texto e pedir para a máquina 'melhorar a escrita', 'deixar mais formal', 'simplificar a linguagem', 'corrigir ortografia e gramática', 'encurtar', 'alongar' ou 'mudar o tom', como é o exemplo do Gemini, que é capaz de editar o texto diretamente no Google Docs (ver Apêndice). Prefira esse tipo de opção mais detida em pequenos trechos, evitando opções generalistas que escrevem trechos completos, como 'escrever introdução", "(conclusão)' ou 'escrever com argumentos opostos' (ver Apêndice). Mas todas essas opções, na prática, significam que seu texto vai ser reescrito por uma IA generativa.", "Da mesma maneira, ao usar chats de grandes modelos de linguagem, como ChatGPT, Qwen, DeepSeek e afins, sempre prefira prompts que peçam para revisar ou melhorar o trecho com 'justificativas para as mudanças', o que garante que você compreenda as razões pelas quais a máquina está mexendo no seu texto e te exercita a compreender tais sugestões. Esse exercício de avaliação das justificativas funciona como prática reflexiva, utilizando a IA como um 'espelho' para testar a robustez dos próprios", "argumentos (Jin et al., 2025). Uma alternativa é solicitar que o chat ofereça 'duas ou mais opções de correção'. Dessa maneira, você poderá observar as diferentes alternativas e construir seu próprio texto. A experiência mostra que a familiaridad

In [228]:
executar_teste8()

In [229]:
executar_teste9()

In [230]:
executar_teste10()

In [271]:
# Mostrar tabela
executar_tabela()

,Arquivo,Teste,Estratégia,Configuração,Qtd. chunks,Tamanho médio,Tamanho mínimo,Tamanho máximo,Chunks sobrepostos,Overlap (%),Tokens estimados,Chunks
0,attention_is_all_you_need.md,1,Fixo,"200 caracteres, overlap 0",245,192.89,117,200,0.0,0.0,11814.0,"[Provided proper attribution is provided, Goog..."
1,attention_is_all_you_need.md,2,Fixo,"500 caracteres, overlap 0",98,492.66,425,500,0.0,0.0,12070.0,"[Provided proper attribution is provided, Goog..."
2,attention_is_all_you_need.md,3,Fixo,"1000 caracteres, overlap 0",49,993.20,937,1000,0.0,0.0,12167.0,"[Provided proper attribution is provided, Goog..."
3,attention_is_all_you_need.md,4,Fixo,"2000 caracteres, overlap 0",25,1951.04,956,2000,0.0,0.0,12194.0,"[Provided proper attribution is provided, Goog..."
4,attention_is_all_you_need.md,5,Fixo + overlap,"500 caracteres, overlap 50",109,491.54,357,500,108.0,10.0,13394.0,"[Provided proper attribution is provided, Goog..."
5,attention_is_all_you_need.md,6,Fixo + overlap,"500 caracteres, overlap 200",163,492.30,357,500,162.0,40.0,20061.0,"[Provided proper attribution is provided, Goog..."
6,attention_is_all_you_need.md,7,Por parágrafo,"500 caracteres, overlap 50",136,358.71,22,499,NaN,NaN,NaN,"[Provided proper attribution is provided, Goog..."
7,attention_is_all_you_need.md,8,Sentenças agrupadas,3 sentenças por chunk,5,10086.60,1620,14045,NaN,NaN,NaN,[{'texto': 'Provided proper attribution is pro...
8,attention_is_all_you_need.md,9,Recursive Character,"500 caracteres, overlap 50",137,364.13,26,499,NaN,NaN,NaN,"[Provided proper attribution is provided, Goog..."
9,attention_is_all_you_need.md,10,Markdown / estrutura semântica,"#, ##, ###",28,1750.11,12,10946,NaN,NaN,NaN,"[Provided proper attribution is provided, Goog..."

In [284]:
# Visualizar o JSON antes de salvar caos precise
visualizar_json()

[
    {
        "Arquivo":"escrita_academica_ia.md",
        "Teste":1,
        "Qtd. chunks":212,
        "Tamanho médio":196.92,
        "Tamanho mínimo":23,
        "Tamanho máximo":200,
        "Chunks sobrepostos":0,
        "Overlap (%)":0.0,
        "Tokens estimados":10437,
        "Chunk":[
            "## Escrita acadêmica ética, responsável e humana com inteligência artificial\n\n<!-- image -->\n\nRafael Cardoso Sampaio\n\n## I ✉\n\nI Programa Pós-Graduação em Ciência Política, Universidade Federal do Para",
            "ná, Curitiba, PR, Brasil.\n\nPalavras-chave: escrita acadêmica, integridade científica, Inteligência Artificial Generativa, autoria, revisão narrativa.\n\nRESUMO Introdução: A rápida disseminação da intel",
            "igência artificial generativa (IAG) transformou práticas de escrita acadêmica, ampliando a eficiência, mas levantando preocupações sobre autoria, integridade, privacidade e desenvolvimento cognitivo.",
            "A literatura recente tem se concentrado em debates normativos e em políticas institucionais sobre autoria e transparência, mas oferece pouca orientação operacional sobre como utilizar a IA sem comprom",
            "eter a formação intelectual, especialmente entre jovens pesquisadores(as). Este artigo busca preencher essa lacuna ao propor um método estruturado de uso ético, responsável e humano da IA. Materiais e",
            "métodos: Oestudo realiza uma revisão narrativa de literatura sobre riscos associados à escrita com IA (e.g., diluição da autoria, descarregamento cognitivo, vieses, privacidade e 'alucinações') e int",
            "egra essa revisão com documentos normativos e diretrizes institucionais. A partir dessa síntese, o artigo desenvolve um guia prático composto por cinco fases metodológicas para orientar o uso crítico",
            "da tecnologia. Resultados: Oguia proposto organiza o processo de escrita em etapas: planejamento humano prévio; escrita assistida e curadoria crítica; apropriação e reescrita autoral; verificação rigo",
            "rosa de fatos, fontes e lógica argumentativa; e responsabilidade final com declaração transparente do uso de IA. Cada fase fornece salvaguardas para mitigar riscos cognitivos, éticos e epistêmicos, pr",
            "eservando a agência autoral. Discussão: Argumenta-se que o uso ético da IA depende menos de proibições formais e mais do desenvolvimento de práticas de vigilância intelectual, documentação e reflexão",
            "contínua. Embora o processo reduza parte da eficiência oferecida pela IA, contribui para fortalecer competências cognitivas, proteger a integridade científica e equilibrar inovação tecnológica com res",
            "ponsabilidade humana.\n\nRecebido em 23 de Julho de 2025. Aprovado em 5 de Novembro de 2025. Aceito em 2 de Dezembro de 2025.\n\nEditor Científico: Adriano Codato\n\nEditor Associado: Adriano Codato\n\niD\n\n<!",
            "-- image -->\n\n<!-- image -->\n\n## I. Introdução\n\nOficina de Escrita Acadêmica\n\nRevista de Sociologia e Política\n\nDOI 10.1590\/1678-98732433e018\n\nA integração da inteligência artificial generativa (IAG)",
            "na produção de conhecimento acadêmico, acelerada por ferramentas como o ChatGPT, evoluiu rapidamente de uma postura de cautela para uma adoção ampla, motivada especialmente pela promessa de maior efic",
            "iência. A capacidade de automatizar ou acelerar diversas fases do trabalho acadêmico gerou otimismo (Pereira et al., 2024). Contudo, essa incorporação massiva também levanta questionamentos sobre a in",
            "tegridade da pesquisa, a originalidade do pensamento e o desenvolvimento das competências cognitivas dos próprios acadêmicos (Lopes et al., 2024; Sampaio et al., 2024).\n\nA resposta inicial da academia",
            "concentrou-se em debates normativos e filosóficos. Uma parte considerável da literatura recente dedicou-se a investigar os limites da autoria, questionando se uma entidade não humana poderia ser cred",
            "itada em trabalhos científicos. A conclusão predominante é que a IA funciona como ferramenta, pois não possui agência ou responsabilidade legal e moral por suas produções (Resnik &amp; Hosseini, 2025)",
            ". Em paralelo, outro foco dominante foi a criação de políticas institucionais, que frequentemente enquadram o uso de IA sob a ótica da desonestidade acadêmica, refletindo a preocupação em proteger os",
            "valores tradicionais da produção de conhecimento e valorizando práticas de total transparência (Trindade &amp; Oliveira, 2024).\n\nApesar de relevante, a discussão normativa vigente deixa uma lacuna de",
            "orientação prática para estudantes e jovens pesquisadores sobre como utilizar a IA de forma ética, sem comprometer o desenvolvimento intelectual (Winberg et al., 2024). A ausência de um método claro a",
            "grava os perigos às fundações cognitivas e criativas da produção de conhecimento, manifestando-se em três áreas críticas.\n\nO primeiro risco diz respeito à diluição da autoria. A autoria manifesta a vo",
            "z singular de um pesquisador, mas a colaboração com IA pode esvaziar o processo criativo ao transferir tarefas intelectuais para a máquina (Floridi, 2025). Estudos demonstram que, mesmo melhorando a q",
            "ualidade textual, o uso de IA pode reduzir a satisfação intrínseca que alimenta a motivação acadêmica (Mei et al., 2025). Essa delegação pode levar à fixação de ideias e à redução da autoconfiança cri",
            "ativa, uma vez que a criatividade humana opera com base em associações idiossincráticas, enquanto a IA gera textos derivativos e estatisticamente prováveis (Lopes et al., 2024).\n\nO segundo risco envol",
            "ve o descarregamento cognitivo ( cognitive offloading ). A delegação de tarefas mentais diminui o engajamento com o pensamento crítico e a aprendizagem autônoma. Evidências mostram que o uso de IA sem",
            "salvaguardas resulta em desempenho inferior em avaliações posteriores, sugerindo que o suporte tecnológico contínuo mina a resolução independente de problemas (Jin et al., 2025; Lee et al., 2025). Co",
            "m o tempo, essa dependência pode atrofiar capacidades cognitivas essenciais (Lopes et al., 2024; Sampaio et al., 2024).\n\nO terceiro risco tange à privacidade e propriedade intelectual. Ao interagir co",
            "m ferramentas de IA, pesquisadores expõem ideias e rascunhos ao treinamento de modelos, gerando questões de confidencialidade (Winberg et al., 2024). A falta de transparência sobre o uso de dados prot",
            "egidos agrava o cenário (Bai et al., 2024; Sampaio et al., 2024). Além disso, a natureza derivativa dos modelos cria riscos tangíveis de plágio inadvertido (Pereira et al., 2024).\n\nEste artigo busca p",
            "reencher a lacuna de orientação prática, oferecendo um guia metodológico para o escrita acadêmica ética, responsável e humana com inteligência artificial com ênfase na Ciência Política e voltado espec",
            "ialmente para jovens pesquisadores e estudantes ainda receosos em utilizar a IA em seus trabalhos. O uso ético refere-se à adesão aos princípios de integridade científica (não fabricar dados, não plag",
            "iar); o uso responsável tange à transparência algorítmica e à privacidade de dados de pesquisa; já o uso humano diz respeito à preservação da agência e da voz do pesquisador, impedindo que a tecnologi",
            "a substitua o pensamento crítico.\n\nO guia é estruturado em cinco fases que orientam o pesquisador para uma colaboração ética e responsável, assegurando que a autoria humana permaneça central no proces",
            "so. Nesse sentido, em vez de focar somente no que evitar, o objetivo é mostrar como unir a eficiência da máquina com a prevalência do pensamento humano, lidando diretamente com os três riscos aqui apr",
            "esentados.\n\n## II. Guia prático para uso ético, responsável e humano da IA generativa na escrita acadêmica\n\nDiante de tais desafios, elaboramos um guia prático composto por sete etapas a serem observa",
            "das durante a escrita com IA buscando equilíbrio entre um uso ético, responsável e que valorize o humano. O Quadro 1 resume as etapas para efeitos didáticos.\n\nQuadro 1 - Etapas para uso ético, respons",
            "ável e humano da IA na escrita acadêmica\n\n|              | Fase                                       | Foco Principal                                                 | Objetivo",
            "|\n|--------------|--------------------------------------------|-------------------------------------------------------------",
            "---|------------------------------------------------------------------------------------------------------------|\n| Pré- escrita | 1. Planejamento humano para o uso de IA    | Estruturação pré-IA, pro",
            "teção de dados e engenharia de prompts | Garantir a intenção autoral, proteger dados de pesquisa e dominar princípios de interação com IA.          |\n| Escrita      | 2. Escrita assistida e cu- radori",
            "a crítica | Brainstorming , análise e revisão contínua                     | Usar a IA para expandir ideias, aprofundar refle- xão crítica e refinar progressivamente o conteúdo.       |\n|",
            "| 3. Apropriação e reescrita autoral         | Transformação e personalização do texto                        | Infundir a voz, pensamento e estilo do autor, ga- rantindo originalidade e evitando mar",
            "cas algorít- micas. |\n| Pós- escrita | 4. Verificação rigorosa de fatos e fontes  | Validação independente de infor- mações                        | Assegurar a precisão factual, bibliográfica, lógica",
            "e ausência de plágio.                                  |\n|              | 5. Responsabilidade final e transparência  | Accountability e declaração de uso                             | Assumir respons",
            "abilidade integral pelo trabalho e declarar transparentemente o uso de IA.                  |\n\nFonte: elaborado pelo autor (2025).\n\n## II.1. Fase 1: planejamento humano para o uso de IA\n\nA proteção de",
            "dados sensíveis que possam identificar participantes de uma pesquisa é uma consideração central ao utilizar inteligência artificial. A inserção de qualquer informação confidencial, como relatos pesso",
            "ais ou dados que permitam a identificação de indivíduos, deve ser evitada em plataformas públicas de IA. O manejo inadequado dessas informações pode levar a violações de privacidade e ao descumpriment",
            "o de regulamentações de proteção de dados (Trindade &amp; Oliveira, 2024). A anonimização completa dos dados, removendo quaisquer identificadores pessoais antes da interação com ferramentas de IA, é r",
            "ecomendada para salvaguardar a confidencialidade dos participantes.\n\nOutra dimensão de cuidado refere-se à preservação do ineditismo e do capital intelectual da pesquisa. Pesquisadores manifestam apre",
            "ensão de que seus achados originais, uma vez inseridos em uma plataforma de IA, possam se tornar parte da informação geral disponível online. Os modelos de linguagem são continuamente treinados com os",
            "dados que recebem, e qualquer informação fornecida pode ser incorporada ao seu conjunto de treinamento e, eventualmente, ser reapresentada em interações com outros usuários (Pereira et al., 2024; Sam",
            "paio et al., 2024). Como cada plataforma estabelece suas próprias regras quanto à privacidade dos dados e ao uso dessas informações para treinamento dos modelos, o pesquisador deve conhecer as polític",
            "as de cada ferramenta antes de seu uso.\n\nAinda antes da escrita com IA, a principal orientação é: 'nunca comece pelo chat'. Toda escrita acadêmica rigorosa deve ser iniciada fora das ferramentas de in",
            "teligência artificial. O pesquisador deve primeiro estabelecer as fundações intelectuais do trabalho mapeando a tese central, formulando perguntas de pesquisa e esboçando o esqueleto do texto. Essa es",
            "truturação prévia fortalece a intenção autoral e mitiga que o algoritmo dite a narrativa ou limite o escopo criativo (Pereira et al., 2024; Mollick &amp; Mollick, 2024). A criatividade genuína emerge",
            "de conexões inesperadas e pensamento que vão além de dados de treinamento, enquanto a IA opera com padrões estatísticos de alta probabilidade, tornando-se usualmente inadequada para inovação conceitua",
            "l (Lopes et al., 2024; Resnik &amp; Hosseini, 2025).\n\nNa pesquisa em Ciência Política, isso significa, entre outras coisas, definir o desenho de pesquisa de forma independente. Antes de solicitar à IA",
            "que\n\n'escreva uma introdução', o pesquisador deve ter clareza sobre quatro elementos. O primeiro é a pergunta de pesquisa, que delimita o que está sendo investigado e, preferencialmente, explicita um",
            "a relação causal a ser testada, por exemplo 'Qual o impacto das emendas parlamentares na coesão partidária no Brasil pós-2018?'. O segundo é a hipótese de trabalho, que oferece uma resposta provisória",
            "para guiar o estudo. O terceiro é o marco teórico, que define as lentes conceituais da análise, como institucionalismo de escolha racional ou sociologia política. O quarto é a estratégia metodológica",
            ", que define como a hipótese será testada empiricamente, seja por métodos quantitativos, qualitativos ou mistos.\n\nDefinido o planejamento, o pesquisador deve escolher as ferramentas e dominar os princ",
            "ípios de interação com a IA. Há uma vasta gama de ferramentas disponíveis (ver Sampaio et al., 2024; Trindade &amp; Oliveira, 2024). As plataformas de IA geralmente oferecem algum tipo de editor de te",
            "xto com possibilidades de escrita, dentre os quais você deverá escolher (ver Apêndice). Não obstante, muitas ferramentas funcionam como extensões que você pode adicionar ao seu editor de texto, como o",
            "Microsoft Word e o Google Docs, sendo que as próprias empresas já embutiram ferramentas do tipo em seus editores. Aqui, o principal cuidado é que algumas ferramentas são especializadas na escrita aca",
            "dêmica e outras são generalistas, merecendo mais cuidado, além disso, cada plataforma estabelece suas próprias regras quanto à privacidade dos dados e ao uso dessas informações para treinamento dos mo",
            "delos.\n\nOs chats dos modelos de linguagem, como ChatGPT, DeepSeek e afins, também podem auxiliar na escrita acadêmica. A qualidade dos resultados é diretamente proporcional à precisão do comando forne",
            "cido, prática conhecida como 'engenharia de prompts ' (Trindade &amp; Oliveira, 2024). Em vez de fazer perguntas genéricas, o pesquisador deve assumir o papel de um 'designer de narrativas', como suge",
            "re Floridi (2025), especificando os requisitos, restrições e parâmetros da tarefa (para mais, ver Sampaio &amp; Figueiredo, 2025).\n\nGrosso modo, deve-se atribuir um papel ou função específica à IA par",
            "a converte-la em uma assistente especializada e não em ferramenta generalista. Comandos como 'atue como pesquisador sênior especialista em instituições políticas e relações Executivo Legislativo' ou '",
            "assuma o papel de um parecerista de periódico e me dê sugestões e pontos a serem melhorados no seguinte texto' tendem a ser efetivos. Essa definição ajuda a IA a compreender o tipo de saída ( output )",
            "esperado e aumenta a precisão das respostas (Mollick &amp; Mollick, 2024).\n\nAlém de definir um papel, o prompt deve fornecer um contexto claro, incluindo a tarefa exata a ser realizada, incluindo o f",
            "ormato , o público-alvo , e o estilo de escrita desejado, o que maximiza a relevância do resultado (Trindade &amp; Oliveira, 2024), como 'corrija esta seção de discussão teórica sobre a governabilidad",
            "e na Nova República pós-1988. O público-alvo são pares acadêmicos especializados em instituições políticas brasileiras. Mantenha tom analítico e formal. Utilize o vocabulário conceitual consagrado pel",
            "a literatura brasileira sobre o presidencialismo de coalizão, incluindo conceitos como 'poderes de agenda', 'disciplina partidária', 'formação de gabinetes' e 'custos de transação legislativos'. A seç",
            "ão deve ter entre 1.500 e 2.000 palavras, estruturada em parágrafos argumentativos sem uso de listas ou marcadores. Justifique as alterações realizadas ao texto'. Em muitos casos, é bom fornecer conte",
            "xtos maiores, como anexar um artigo ou colar um texto dentro da temática que você deseja escrever.\n\n## II.2. Fase 2: geração de insumos, curadoria crítica e refinamento iterativo\n\nUma vez escolhidas a",
            "s ferramentas e dominados os princípios de engenharia de prompts , torna-se possível interagir com a inteligência artificial de maneira controlada, utilizando-a como um recurso de apoio para ampliar o",
            "repertório criativo e analítico, sem substituir a capacidade de análise crítica. Um uso profícuo consiste em solicitar à IA a geração de listas de ideias sobre um tópico, a sugestão de diferentes âng",
            "ulos para um argumento, a criação de exemplos para ilustrar conceitos ou a elaboração de analogias para teorias complexas (Mollick &amp; Mollick, 2024). Essa abordagem transforma a IA em uma 'parceira",
            "de brainstorming ' ou em uma 'fonte de inspiração' e uma 'bússola' que aponta novas direções (Jin et al., 2025). A IA pode aumentar a fluência e a flexibilidade do pensamento divergente, auxiliando n",
            "a superação de bloqueios criativos.\n\nAssim como o trabalho não começa no chat, ele também não termina nele. Nenhuma resposta produzida por IA deve ser tratada como versão final. Cada trecho de texto p",
            "roduzido pela máquina é um protótipo, um rascunho inicial que exige um rigoroso processo de curadoria e apropriação humana. Em vez de aceitar passivamente a primeira sugestão, que frequentemente é gen",
            "érica e carece de profundidade (Pereira et al., 2024), o pesquisador deve guiar a ferramenta com comandos específicos, a exemplo de 'sua sugestão anterior foi útil, mas agora a refine para incorporar",
            "o debate sobre a execução de emendas parlamentares como moeda de troca nas relações Executivo-Legislativo e remover as generalizações sobre barganha política em sistemas presidencialistas'.\n\nEsta fase",
            "se define por ciclos curtos e contínuos de revisão, nos quais o pesquisador lê criticamente o material, identifica imprecisões, superficialidades ou lacunas argumentativas ('Escrever', 'Filtrar', 'Ve",
            "rificar'), e utiliza essas observações para refinar seus prompts em um diálogo contínuo com a ferramenta (Bai et al., 2024). Ess e ciclo de interação e refinamento progressivo não só melhora a qualida",
            "de do resultado da máquina, mas também ajuda o próprio pesquisador a clarificar seus objetivos e a aprofundar seu pensamento crítico (Lee et al., 2025), mantendo total agência e controle sobre o conte",
            "údo (Floridi, 2025).\n\nUma forma de aprofundar esse processo é inverter a dinâmica da interação, solicitando que a IA atue como uma 'entrevistadora' ou 'crítica socrática' para desafiar a lógica do tra",
            "balho humano. Comandos como 'leia este parágrafo sobre o conceito de polarização afetiva e aponte três falhas lógicas ou contra-argumentos baseados na literatura recente' ou 'aja como um aluno inician",
            "te e peça para eu explicar este conceito em termos simples' forçam o autor a defender e a clarificar suas ideias, quebrando o que Mollick &amp; Mollick (2024) denominam 'ilusão de profundidade explana",

In [283]:
# gerar Arquivo Json
gerar_json()

Arquivo salvo em: resultados.json

# *TESTES*:
Funções principais
1. Teste do 1 ao 6

In [242]:
# CALCULO PRINCIPAL DOS TESTE 1 AO 6
def chunk_calc(text, tamanho, overlap=0):
    splitter = CharacterTextSplitter(
        separator="",
        chunk_size=tamanho,
        chunk_overlap=overlap
    )

    chunks = splitter.split_text(text)
    return chunks

2. Teste 7 - Paragrafo

In [250]:
def analise_paragrafos(text, arquivo):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=5,
        separators=["\n\n", "\n", " ", ""]
    )

    # Define metadados before creating chunks
    metadados = {
        "teste": 7,
        "arquivo": arquivo.name,
        "caminho": str(arquivo),
        "estrategia": "Por parágrafo"
    }

    # Create chunks first
    chunks = splitter.create_documents(
        [text],
        metadatas=[metadados]
    )

    # Now, calculate tamanhos from the created chunks
    tamanhos = [
        len(chunk.page_content)
        for chunk in chunks
    ]

    return {
        "Qtd. chunks": len(chunks),
        "Tamanho médio": round(sum(tamanhos) / len(tamanhos), 2),
        "Tamanho mínimo": min(tamanhos),
        "Tamanho máximo": max(tamanhos),
        "Chunks": [chunk.page_content for chunk in chunks]
    }

3. Teste 8 - Sentenças agrupadas

In [181]:
# Teste 8 FUNCIONADO

def analise_sentencas(texto, arquivo):

    splitter = NLTKTextSplitter()

    sentencas = splitter.split_text(texto)

    chunks = []

    for i in range(0, len(sentencas), 3):

        grupo = sentencas[i:i + 3]

        texto_chunk = " ".join(grupo)

        chunks.append({
            "texto": texto_chunk,
            "quantidade_sentencas": len(grupo),
            "metadados": {
                "arquivo": arquivo.name,
                "caminho": str(arquivo),
                "teste": 8,
                "estrategia": "Sentenças agrupadas",
                "sentencas": len(grupo)
            }
        })

    return chunks

In [182]:
def analisar_teste_8(chunks):

    tamanhos = [
        len(chunk["texto"])
        for chunk in chunks
    ]


    return {
        "Qtd. chunks": len(chunks),
        "Tamanho médio": round(sum(tamanhos) / len(tamanhos), 2),
        "Tamanho mínimo": min(tamanhos),
        "Tamanho máximo": max(tamanhos),
        "Chunks": chunks
    }

4. Teste 9 Recursivo

In [191]:
def analise_recursivo(texto, arquivo):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=50,
        separators=[
            "\n\n",
            "\n",
            " ",
            ""
        ]
    )
    documentos = splitter.create_documents(
        [texto],
        metadatas=[{
            "arquivo": arquivo.name,
            "caminho": str(arquivo),
            "teste": 9,
            "estrategia": "Recursive Character",
            "chunk_size": 500,
            "chunk_overlap": 50,
        }]
    )
    return documentos

In [198]:
def analisar_chunks_documentos(chunks):

    tamanhos = [
        len(chunk.page_content)
        for chunk in chunks
    ]

    return {
        "Qtd. chunks": len(chunks),
        "Tamanho médio": round(sum(tamanhos) / len(tamanhos), 2),
        "Tamanho mínimo": min(tamanhos),
        "Tamanho máximo": max(tamanhos),
        "Chunks": [chunk.page_content for chunk in chunks]
    }

5. Teste 10

In [201]:
def teste_10_markdown(texto, arquivo):

    headers = [
        ("#", "Header 1"),
        ("##", "Header 2"),
        ("###", "Header 3")
    ]

    splitter = MarkdownHeaderTextSplitter(
        headers_to_split_on=headers,
        strip_headers=False
    )

    documentos = splitter.split_text(texto)


    # Adicionar informações do arquivo/teste
    for doc in documentos:
        doc.metadata["arquivo"] = arquivo.name
        doc.metadata["caminho"] = str(arquivo)
        doc.metadata["teste"] = 10
        doc.metadata["estrategia"] = "Markdown / estrutura semântica"


    return documentos

In [259]:
# Não sei se precisa, mas para analisar quantas partes do chunk existem dentro de outros chunks
def contar_chunks_sobrepostos(chunks):

    contador = 0

    for i in range(1, len(chunks)):

        chunk_anterior = chunks[i - 1]
        chunk_atual = chunks[i]

        tamanho_maximo = min(
            len(chunk_anterior),
            len(chunk_atual)
        )

        possui_overlap = False

        for tamanho in range(1, tamanho_maximo + 1):

            if chunk_anterior[-tamanho:] == chunk_atual[:tamanho]:
                possui_overlap = True
                break

        if possui_overlap:
            contador += 1

    return contador
# -------------------------------------------------------------------------------------
# Realiza a analize dos chunks
def analisar_chunks(chunks, chunk_size, chunk_overlap):

    tamanhos = [len(chunk) for chunk in chunks]

    # Quantidade de chunks que possuem overlap
    if chunk_overlap > 0:
        qtd_sobrepostos = contar_chunks_sobrepostos(chunks)
        #qtd_sobrepostos = max(len(chunks) - 1, 0)
    else:
        qtd_sobrepostos = 0

    # Percentual configurado de overlap
    percentual_overlap = (
        chunk_overlap / chunk_size * 100
        if chunk_size > 0
        else 0
    )

    # aqui dá para comparar com oque o embedding vai realmente retornar depois!
    # Estimativa simples:
    # aproximadamente 4 caracteres por token
    total_caracteres = sum(tamanhos)
    tokens_estimados = round(total_caracteres / 4)

    return {
        "Qtd. chunks": len(chunks),
        "Tamanho médio": round(sum(tamanhos) / len(tamanhos), 2),
        "Tamanho mínimo": min(tamanhos),
        "Tamanho máximo": max(tamanhos),
        "Chunks sobrepostos": qtd_sobrepostos,
        "Overlap (%)": round(percentual_overlap, 2),
        "Tokens estimados": tokens_estimados

    }

In [ ]:
# Definindo os testes a serem realizados 1 - 6
testes = [
    {
        "Teste": 1,
        "Estratégia": "Fixo",
        "Configuração": "200 caracteres, overlap 0",
        "chunk_size": 200,
        "chunk_overlap": 0
    },
    {
        "Teste": 2,
        "Estratégia": "Fixo",
        "Configuração": "500 caracteres, overlap 0",
        "chunk_size": 500,
        "chunk_overlap": 0
    },
    {
        "Teste": 3,
        "Estratégia": "Fixo",
        "Configuração": "1000 caracteres, overlap 0",
        "chunk_size": 1000,
        "chunk_overlap": 0
    },
    {
        "Teste": 4,
        "Estratégia": "Fixo",
        "Configuração": "2000 caracteres, overlap 0",
        "chunk_size": 2000,
        "chunk_overlap": 0
    },
    {
        "Teste": 5,
        "Estratégia": "Fixo + overlap",
        "Configuração": "500 caracteres, overlap 50",
        "chunk_size": 500,
        "chunk_overlap": 50
    },
    {
        "Teste": 6,
        "Estratégia": "Fixo + overlap",
        "Configuração": "500 caracteres, overlap 200",
        "chunk_size": 500,
        "chunk_overlap": 200
    }
]

# Funções de Execução

1-6. EXECUTAVEL TESTE

In [243]:
# Aqui é onde as coisas são executadas
# Ele pega os arquivos com o PATH definido lá em cima
# Faz um loop e manda calcular e depois analizar os chunks para retornar oque é pedido
# Ele vai guardando cada resultado dentro de resultados = []
def executar():
    for arquivo in arquivos:

        texto = arquivo.read_text(encoding="utf-8")

        analise = analise_paragrafos(
            texto,
            arquivo
        )

        print(analise)

        for teste in testes:

            chunks = chunk_calc(
                texto,
                teste["chunk_size"],
                teste["chunk_overlap"]
            )

            analise = analisar_chunks(
                chunks,
                teste["chunk_size"],
                teste["chunk_overlap"]
            )

            resultados_todos.append({
                "Arquivo": arquivo.name,
                "Teste": teste["Teste"],
                "Estratégia": teste["Estratégia"],
                "Configuração": teste["Configuração"],
                **analise,
                'Chunks': chunks
            })

7. EXECUTAVEL TESTE

In [256]:
def executar_teste7():
  for arquivo in arquivos:

    texto = arquivo.read_text(encoding="utf-8")

    analise = analise_paragrafos(
        texto,
        arquivo
    )

    print(analise)

    resultados_todos.append({
        "Arquivo": arquivo.name,
        "Teste": 7,
        "Estratégia": "Por parágrafo",
        "Configuração": "500 caracteres, overlap 50",
        **analise,
    })

8. EXECUTAVEL TESTE

In [186]:
def executar_teste8():
    for arquivo in arquivos:

        texto = arquivo.read_text(encoding="utf-8")

        chunks = analise_sentencas(
            texto,
            arquivo
        )

        analise = analisar_teste_8(chunks)

        resultados_todos.append({
            "Arquivo": arquivo.name,
            "Teste": 8,
            "Estratégia": "Sentenças agrupadas",
            "Configuração": "3 sentenças por chunk",
            **analise
        })

9. EXECUTAVEL TESTE

In [197]:
def executar_teste9():
    for arquivo in arquivos:
      texto = arquivo.read_text(encoding="utf-8")

      chunks = analise_recursivo(
          texto,
          arquivo
      )

      analise = analisar_chunks_documentos(chunks)

      resultados_todos.append({
          "Arquivo": arquivo.name,
          "Teste": 9,
          "Estratégia": "Recursive Character",
          "Configuração": "500 caracteres, overlap 50",
          **analise
      })

10. EXECUTAVEL TESTE

In [202]:
def executar_teste10():
  for arquivo in arquivos:

    texto = arquivo.read_text(encoding="utf-8")

    chunks = teste_10_markdown(
        texto,
        arquivo
    )

    analise = analisar_chunks_documentos(chunks)

    resultados_todos.append({
        "Arquivo": arquivo.name,
        "Teste": 10,
        "Estratégia": "Markdown / estrutura semântica",
        "Configuração": "#, ##, ###",
        **analise
    })

# Geração e visualização da Tabela dos Resultados com pd

In [275]:
def executar_tabela():
    df_resultados_todos = pd.DataFrame(resultados_todos)

    display(df_resultados_todos)

In [286]:
caminho = "/resultados.xlsx"
def salvar_excel():
    df_resultados_todos = pd.DataFrame(resultados_todos)

    df_resultados_todos.to_excel(
        caminho,
        index=False
    )

    print(f"Arquivo salvo em: {caminho}")

# Geração e Visualização do JSON

In [289]:
def visualizar_json():
    json_resultados = df_resultados_todos.to_json(
      orient="records",
      indent=4,
      force_ascii=False
    )

    print(json_resultados)

In [288]:
caminho_json = "resultados.json"
def gerar_json():
    with open(caminho_json, "w", encoding="utf-8") as arquivo:
        json.dump(
            resultados_todos,
            arquivo,
            ensure_ascii=False,
            indent=4
        )

    print(f"Arquivo salvo em: {caminho_json}")